# Generated by Django 5.0.2 on 2026-05-17 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tct', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teacher',
            options={'ordering': ['name']},
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='course',
        ),
    ]
